<?php

/**
 * @file
 * Main code.
 */

/**
 * Get count statistic for url.
 *
 * @param $url
 * @param array $networks Can be: twitter, facebook, pluseone, vkontakte,
 *                        mailru, odnoklassniki, pinterest.
 * @return array
 */
function sharek_get_counts($url, $networks) {
  $sharek = new Sharek();

  return $sharek->getCount($url, $networks);
}

/**
 * Implements hook_theme().
 */
function sharek_theme() {
  $path = drupal_get_path('module', 'sharek') . '/theme';

  return array(
    'sharek' => array(
      'variables' => array(
        'share_url' => NULL,
        'label' => NULL,
        'popup_width' => NULL,
        'popup_height' => NULL,
      ),
      'template' => 'sharek',
      'pattern' => 'sharek__',
      'path' => $path,
    ),
  );
}

function example() {
  $result = array();
  foreach (module_implements('hook_theme') as $module) {
    // will call all modules implementing hook_hook_name and
    // push the results onto the $result array
    $result[] = module_invoke($module, 'hook_theme');
  }

  dpm($result);
}

/**
 * Return button.
 *
 * @param string $network Network name.
 * @param array $options Must contain at least 'share_url' value. Also can get
 *                       'label', 'popup_width' and 'popup-height'.
 * @param string $style Style name.
 * @return string
 * @throws \Exception
 * @internal param $url
 */
function sharek_get_button($network, $options, $style = NULL) {
  $options['network'] = $network;
  return theme('sharek__'. $network, $options);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_sharek(&$variables) {
  // Set default values.
  $variables['label'] == NULL ? $variables['label'] = t('Share') : false;
  $variables['popup_width'] == NULL ? $variables['popup_width'] = 600 : false;
  $variables['popup_height'] == NULL ? $variables['popup_height'] = 450 : false;
}
