<?php

/**
 * @file
 * Main code.
 */


/**
 * Implements hook_preprocess().
 */
function sharek_preprocess_page(&$variables, $hook) {
  $test = new Sharek();
  $url = 'http://google.com/';
  dpm(sharek_get_counts($url, array('vkontakte', 'facebook', 'pluseone')));
}

/**
 * Get count statistic for url.
 *
 * @param $url
 * @param array $networks Can be: twitter, facebook, pluseone, vkontakte,
 *                        mailru, odnoklassniki, pinterest.
 * @return array
 */
function sharek_get_counts($url, $networks) {
  $sharek = new Sharek();

  return $sharek->getCount($url, $networks);
}