<?php


/**
 * Implements hook_preprocess_HOOK().
 */
function sharekit_preprocess_page(&$variables) {
  $sharekit = new \Drupal\sharekit\ShareKit();
  $sharekit->setStyle('test');
  $sharekit->shareLoad('facebook');
  ksm($sharekit->render());

}


/**
 * Implements hook_theme().
 */
function sharekit_theme($existing, $type, $theme, $path) {
  return [
    'sharekit' => array(
      'variables' => array(
        'items' => NULL,
      ),
      'template' => 'sharekit',
      'pattern' => 'sharekit__',
    ),
  ];
}