<?php

/**
 * @file
 * Main code.
 */

/**
 * Get count statistic for url.
 *
 * @param $url
 * @param array $networks Can be: twitter, facebook, pluseone, vkontakte,
 *                        mailru, odnoklassniki, pinterest.
 * @return array
 */
function sharekit_get_counts($url, $networks) {
  $sharekit = new ShareKit();

  return $sharekit->getCount($url, $networks);
}

/**
 * Implements hook_theme().
 */
function sharekit_theme() {
  $path = drupal_get_path('module', 'sharekit') . '/theme';

  return array(
    'sharekit' => array(
      'variables' => array(
        'share_url' => NULL,
        'share_title' => NULL,
        'label' => NULL,
        'popup_width' => NULL,
        'popup_height' => NULL,
      ),
      'template' => 'sharekit',
      'pattern' => 'sharekit__',
      'path' => $path,
    ),
  );
}

/**
 * Return button.
 *
 * @param string $network Network name.
 * @param array $options Must contain at least 'share_url' value. Also can get
 *                        'label', 'popup_width' and 'popup-height'.
 * @param string $style Style name.
 * @return string
 * @throws \Exception
 * @internal param $url
 */
function sharekit_get_button($network, $style = NULL, $options = array()) {
  $options['network'] = $network;
  $options['style'] = $style;

  $suggestions = array();
  if ($style) {
    $suggestions[] = 'sharekit__' . $network . '__' . $style;
    $suggestions[] = 'sharekit__' . $style;
  }
  $suggestions[] = 'sharekit__' . $network;
  $suggestions[] = 'sharekit';

  return theme($suggestions, $options);
}

/**
 * Get buttons multiple.
 *
 * @param $networks
 * @param null $style
 * @param array $options
 * @return string
 * @throws \Exception
 */
function sharekit_get_buttons($networks, $style = NULL, $options = array()) {
  $result = '';
  $options['style'] = $style;

  $networks_array = explode(',', str_replace(' ', '', $networks));

  foreach ($networks_array as $key => $network) {
    $options['network'] = $network;

    $suggestions = array();
    if ($style) {
      $suggestions[] = 'sharekit__' . $network . '__' . $style;
      $suggestions[] = 'sharekit__' . $style;
    }
    $suggestions[] = 'sharekit__' . $network;
    $suggestions[] = 'sharekit';

    $result .= theme($suggestions, $options);
  }

  return $result;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function template_preprocess_sharekit(&$variables) {
  // Set default values.
  global $base_url;
  $variables['share_url'] === NULL ? $variables['share_url'] = $base_url . '/' . request_path() : FALSE;
  $variables['share_title'] === NULL ? $variables['share_title'] = drupal_get_title() : FALSE;
  $variables['label'] === NULL ? $variables['label'] = t('Share') : FALSE;
  $variables['popup_width'] === NULL ? $variables['popup_width'] = 600 : FALSE;
  $variables['popup_height'] === NULL ? $variables['popup_height'] = 450 : FALSE;
  $variables['classes_array'][] = $variables['network'];
  $variables['style'] != NULL ? $variables['classes_array'][] = $variables['style'] : $variables['classes_array'][] = 'default';

  // Get current share count.
  $sharekit = new sharekit();
  $count = $sharekit->getCount($variables['share_url'], array($variables['network']));
  $variables['share_count'] = $count[$variables['network']];

  // Add styles only for default style.
  if ($variables['style'] == NULL) {
    drupal_add_css(drupal_get_path('module', 'sharekit') . '/css/sharekit.css');
  }
}

/**
 * Implements hook_process_hook
 */
function template_process_sharekit(&$variables) {
  $variables['attributes'] = drupal_attributes(array(
    'data-social-network' => $variables['network'],
    'data-share-url' => $variables['share_url'],
    'data-share-title' => $variables['share_title'],
    'data-popup-width' => $variables['popup_width'],
    'data-popup-height' => $variables['popup_height'],
  ));
}
